//login
###1
#POST http://localhost:8080/auth/login/{{user_id}}
POST http://localhost:8080/auth/login/6Uj630yjijSYLAEvQ1WL90Tfdra2
Content-Type: application/json

//refresh token
###2
POST http://localhost:8080/auth/token
Content-Type: application/json

{
  "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNlVqNjMweWppalNZTEFFdlExV0w5MFRmZHJhMiIsInBhcnRpY2lwYW50cyI6WyI2MzY0ZTAxZmE3ZWMwODQ5OGRkOWJhOWYiLCI2MzY0ZTA3ZmE3ZWMwODQ5OGRkOWJhYmMiLCI2MzY1MzY1NDQwMDVmZDMwOWEwYTdkMjkiLCI2MzY1MzhkYTQwMDVmZDMwOWEwYTdkNzkiLCI2MzY4OTBlNWFmNDZhZjMzNjAzZjU1MGIiLCI2MzY4YmQyZTZlMzBjMjQ3YzQxMThkNDYiLCI2MzY5MWZiOWVkOTQ5MzQ5MWNjYWEzMGQiLCI2MzY5YjY0MGRiNWM2OTE1ZmU4N2ViZGEiLCI2MzY5YjZlOWRiNWM2OTE1ZmU4N2ViZmYiLCI2MzY5YjkyMmM3ZGZkZGM0MmVhZGJjZTAiLCI2MzY5YmM0YzYyZWE5MmQ2ZDlhYmIyZGQiLCI2MzZhN2JmYzAyMWMyZDkyMGUzYjY5ZDAiLCI2MzgxZDJmZjk3MmUxZGMwNjFiZmE5OTUiXSwiaWF0IjoxNjY5OTA1ODcyLCJleHAiOjE2Njk5MDU4NzJ9.bemgBgZ0sjvi0RICnQBnm2_CS-ABLVkR8NmOdhB7GKU"
}

###logout
PUT http://localhost:8080/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNlVqNjMweWppalNZTEFFdlExV0w5MFRmZHJhMiIsInBhcnRpY2lwYW50cyI6WyI2MzY0ZTAxZmE3ZWMwODQ5OGRkOWJhOWYiLCI2MzY0ZTA3ZmE3ZWMwODQ5OGRkOWJhYmMiLCI2MzY1MzY1NDQwMDVmZDMwOWEwYTdkMjkiLCI2MzY1MzhkYTQwMDVmZDMwOWEwYTdkNzkiLCI2MzY4OTBlNWFmNDZhZjMzNjAzZjU1MGIiLCI2MzY4YmQyZTZlMzBjMjQ3YzQxMThkNDYiLCI2MzY5MWZiOWVkOTQ5MzQ5MWNjYWEzMGQiLCI2MzY5YjY0MGRiNWM2OTE1ZmU4N2ViZGEiLCI2MzY5YjZlOWRiNWM2OTE1ZmU4N2ViZmYiLCI2MzY5YjkyMmM3ZGZkZGM0MmVhZGJjZTAiLCI2MzY5YmM0YzYyZWE5MmQ2ZDlhYmIyZGQiLCI2MzZhN2JmYzAyMWMyZDkyMGUzYjY5ZDAiLCI2MzgxZDJmZjk3MmUxZGMwNjFiZmE5OTUiXSwiaWF0IjoxNjY5OTA2MTY2LCJleHAiOjE2Njk5MDYxNjZ9.WywyXhkQOTNi1YAv-6wJ65m8lLeFEaUeaOCoivrQpy8


###get room
//get room by ID user and room
#GET http://localhost:8080/api/room/{{userId}}&{{roomId}}
GET http://localhost:8080/api/room/A931rAdlZATBBnWaySfO2UuQO8v2&6364e01fa7ec08498dd9ba9e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNlVqNjMweWppalNZTEFFdlExV0w5MFRmZHJhMiIsInBhcnRpY2lwYW50cyI6WyI2MzY0ZTAxZmE3ZWMwODQ5OGRkOWJhOWYiLCI2MzY0ZTA3ZmE3ZWMwODQ5OGRkOWJhYmMiLCI2MzY1MzY1NDQwMDVmZDMwOWEwYTdkMjkiLCI2MzY1MzhkYTQwMDVmZDMwOWEwYTdkNzkiLCI2MzY4OTBlNWFmNDZhZjMzNjAzZjU1MGIiLCI2MzY4YmQyZTZlMzBjMjQ3YzQxMThkNDYiLCI2MzY5MWZiOWVkOTQ5MzQ5MWNjYWEzMGQiLCI2MzY5YjY0MGRiNWM2OTE1ZmU4N2ViZGEiLCI2MzY5YjZlOWRiNWM2OTE1ZmU4N2ViZmYiLCI2MzY5YjkyMmM3ZGZkZGM0MmVhZGJjZTAiLCI2MzY5YmM0YzYyZWE5MmQ2ZDlhYmIyZGQiLCI2MzZhN2JmYzAyMWMyZDkyMGUzYjY5ZDAiLCI2MzgxZDJmZjk3MmUxZGMwNjFiZmE5OTUiXSwiaWF0IjoxNjY5OTA2MTY2LCJleHAiOjE2Njk5MDYxNjZ9.WywyXhkQOTNi1YAv-6wJ65m8lLeFEaUeaOCoivrQpy8

###get user
//get user by id
#GET http://localhost:8080/api/user/{{uid}}
GET http://localhost:8080/api/user/A931rAdlZATBBnWaySfO2UuQO8v2