//create message
###1
#POST http://localhost:8080/api/message/{{userId}}&{{roomId}}
POST http://localhost:8080/api/message/6Uj630yjijSYLAEvQ1WL90Tfdra2&6364e01fa7ec08498dd9ba9e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjJkN2I4YWYyNmE1NTliZDhmOTRkNDA3IiwiaWF0IjoxNjU4Nzk5MDIyfQ.Xi-0E_F_5aqI_zICxPre-4XgRUIazLVIk3iJUviN1gk

{
  "message": "Ymtkbg==",
  "type": "file"
}

###2
//get all message
GET http://localhost:8080/api/message/


###3
//get all message by roomId
#GET http://localhost:8080/api/message/room/{{roomId}}
GET http://localhost:8080/api/message/room/6368bd2e6e30c247c4118d45
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiU0ltNVY3cGVrUFR3aFRaNFRHdzIzRDRGcFRzMSIsInBhcnRpY2lwYW50cyI6WyI2MzY0ZTAxZmE3ZWMwODQ5OGRkOWJhYTciLCI2MzY0ZTA3ZmE3ZWMwODQ5OGRkOWJhYzMiLCI2MzY1MzY1NTQwMDVmZDMwOWEwYTdkMzAiLCI2MzY1MzhkYTQwMDVmZDMwOWEwYTdkODAiLCI2MzY4OTBlNWFmNDZhZjMzNjAzZjU1MGMiLCI2MzZhN2JmYzAyMWMyZDkyMGUzYjY5ZDciLCI2MzZiNDRjY2JjNzVmODc5Zjg2NGU0MmMiLCI2MzgxZDMwMDk3MmUxZGMwNjFiZmE5OWMiXSwiaWF0IjoxNjcwMDQ4MDQ0LCJleHAiOjE2NzAwNDgzNDR9.fPdH3nIZOwm_WriODdIUJwOOGLl2ukbtMfPH11QCk7I


###4
//get pagination
#GET http://localhost:8080/api/message/page/{{roomId}}&{{page}}&{{step}}
GET http://localhost:8080/api/message/page/6364e01fa7ec08498dd9ba9e&0&10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiU0ltNVY3cGVrUFR3aFRaNFRHdzIzRDRGcFRzMSIsInBhcnRpY2lwYW50cyI6WyI2MzY0ZTAxZmE3ZWMwODQ5OGRkOWJhYTciLCI2MzY0ZTA3ZmE3ZWMwODQ5OGRkOWJhYzMiLCI2MzY1MzY1NTQwMDVmZDMwOWEwYTdkMzAiLCI2MzY1MzhkYTQwMDVmZDMwOWEwYTdkODAiLCI2MzY4OTBlNWFmNDZhZjMzNjAzZjU1MGMiLCI2MzZhN2JmYzAyMWMyZDkyMGUzYjY5ZDciLCI2MzZiNDRjY2JjNzVmODc5Zjg2NGU0MmMiLCI2MzgxZDMwMDk3MmUxZGMwNjFiZmE5OWMiXSwiaWF0IjoxNjcwMDQ5NTU4LCJleHAiOjE2NzAwNDk4NTh9.YSdj72-0-q7TMlIlN8R2l4gvF6q0RCtTgdUSkHo4vyM
###5
//delete message
#DELETE http://localhost:8080/api/message/{{msgId}}
DELETE http://localhost:8080/api/message/634ad29c5a7e1578ce47a5f0


###6
//delete all message
#DELETE http://localhost:8080/api/message/
DELETE http://localhost:8080/api/message/


###login
#POST http://localhost:8080/auth/login/{{user_id}}
POST http://localhost:8080/api/auth/login/SIm5V7pekPTwhTZ4TGw23D4FpTs1
Content-Type: application/json

###7
//get page message 
#GET http://localhost:8080/api/message/page/{{roomId}}&{{page}}&{{step}}

#{
#  success: true,
#  data: [
#    {
#      message: {}, //đối tượng message
#      participant: {
#        ... giữ các đối tượng của participant trừ user_id đổi thành user,
#      },
#    }
#  ]
#}

