//create message
###1
#POST http://localhost:8080/api/message/{{userId}}&{{roomId}}
POST http://localhost:8080/api/message/6Uj630yjijSYLAEvQ1WL90Tfdra2&6364e01fa7ec08498dd9ba9e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjJkN2I4YWYyNmE1NTliZDhmOTRkNDA3IiwiaWF0IjoxNjU4Nzk5MDIyfQ.Xi-0E_F_5aqI_zICxPre-4XgRUIazLVIk3iJUviN1gk

{
  "message": "Ymtkbg==",
  "type": "text"
}

###2
//get all message
GET http://localhost:8080/api/message/


###3
//get all message by roomId
#GET http://localhost:8080/api/message/room/{{roomId}}
GET http://localhost:8080/api/message/room/6364e01fa7ec08498dd9ba9e

###4
//get pagination
#GET http://localhost:8080/api/message/page/{{roomId}}&{{page}}&{{step}}
GET http://localhost:8080/api/message/page/6364e01fa7ec08498dd9ba9e&2&2


###5
//delete message
#DELETE http://localhost:8080/api/message/{{msgId}}
DELETE http://localhost:8080/api/message/634ad29c5a7e1578ce47a5f0


###6
//delete all message
#DELETE http://localhost:8080/api/message/
DELETE http://localhost:8080/api/message/


###7
//get page message 
#GET http://localhost:8080/api/message/page/{{roomId}}&{{page}}&{{step}}

#{
#  success: true,
#  data: [
#    {
#      message: {}, //đối tượng message
#      participant: {
#        ... giữ các đối tượng của participant trừ user_id đổi thành user,
#      },
#    }
#  ]
#}

