###create participant
#POST http://localhost:8080/api/participant/:userId&:roomId
POST http://localhost:8080/api/participant/2ZFMFC9EXnbNFvjYLHoaHD8vc&638b07bac6ee51fc3162a903
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNlVqNjMweWppalNZTEFFdlExV0w5MFRmZHJhMiIsInBhcnRpY2lwYW50cyI6WyI2MzY0ZTAxZmE3ZWMwODQ5OGRkOWJhOWYiLCI2MzY0ZTA3ZmE3ZWMwODQ5OGRkOWJhYmMiLCI2MzY1MzY1NDQwMDVmZDMwOWEwYTdkMjkiLCI2MzY1MzhkYTQwMDVmZDMwOWEwYTdkNzkiLCI2MzY4OTBlNWFmNDZhZjMzNjAzZjU1MGIiLCI2MzY4YmQyZTZlMzBjMjQ3YzQxMThkNDYiLCI2MzY5MWZiOWVkOTQ5MzQ5MWNjYWEzMGQiLCI2MzY5YjY0MGRiNWM2OTE1ZmU4N2ViZGEiLCI2MzY5YjZlOWRiNWM2OTE1ZmU4N2ViZmYiLCI2MzY5YjkyMmM3ZGZkZGM0MmVhZGJjZTAiLCI2MzY5YmM0YzYyZWE5MmQ2ZDlhYmIyZGQiLCI2MzZhN2JmYzAyMWMyZDkyMGUzYjY5ZDAiLCI2MzgxZDJmZjk3MmUxZGMwNjFiZmE5OTUiLCI2MzhhZjdjNGFkOGQzOGJhOTJhNTQ4Y2MiLCI2MzhhZmU3N2M2ZWU1MWZjMzE2MmE3M2UiLCI2MzhiMDUwYmM2ZWU1MWZjMzE2MmE4OGEiLCI2MzhiMDdiYWM2ZWU1MWZjMzE2MmE5MDQiXSwiaWF0IjoxNjcwMjUyOTY5LCJleHAiOjE2NzAyNTQ3Njl9.HdwOwkj98N2kriaW07mlnCfxT-hwgyd3aqOr8CsqsYI

###get All Participant
#GET http://localhost:8080/api/participant/
GET http://localhost:8080/api/participant/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiU0ltNVY3cGVrUFR3aFRaNFRHdzIzRDRGcFRzMSIsInBhcnRpY2lwYW50cyI6WyI2MzY0ZTAxZmE3ZWMwODQ5OGRkOWJhYTciLCI2MzY0ZTA3ZmE3ZWMwODQ5OGRkOWJhYzMiLCI2MzY1MzY1NTQwMDVmZDMwOWEwYTdkMzAiLCI2MzY1MzhkYTQwMDVmZDMwOWEwYTdkODAiLCI2MzY4OTBlNWFmNDZhZjMzNjAzZjU1MGMiLCI2MzZhN2JmYzAyMWMyZDkyMGUzYjY5ZDciLCI2MzZiNDRjY2JjNzVmODc5Zjg2NGU0MmMiLCI2MzgxZDMwMDk3MmUxZGMwNjFiZmE5OWMiLCI2MzhhZjdjNGFkOGQzOGJhOTJhNTQ4ZDMiLCI2MzhhZmU3OGM2ZWU1MWZjMzE2MmE3NDUiLCI2MzhiMDUyY2M2ZWU1MWZjMzE2MmE4OTEiLCI2MzhiMDdiYmM2ZWU1MWZjMzE2MmE5MGYiXSwiaWF0IjoxNjcwMjUwNTIxLCJleHAiOjE2NzAyNTIzMjF9.YiADvHENAp1-IlkAjk6tXFY9ovmYcV8dP8HF-fQAeUg

###get Participant by Id
#GET http://localhost:8080/api/participant/{{participantId}}
GET http://localhost:8080/api/participant/6364e01fa7ec08498dd9ba9f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNlVqNjMweWppalNZTEFFdlExV0w5MFRmZHJhMiIsInBhcnRpY2lwYW50cyI6WyI2MzY0ZTAxZmE3ZWMwODQ5OGRkOWJhOWYiLCI2MzY0ZTA3ZmE3ZWMwODQ5OGRkOWJhYmMiLCI2MzY1MzY1NDQwMDVmZDMwOWEwYTdkMjkiLCI2MzY1MzhkYTQwMDVmZDMwOWEwYTdkNzkiLCI2MzY4OTBlNWFmNDZhZjMzNjAzZjU1MGIiLCI2MzY4YmQyZTZlMzBjMjQ3YzQxMThkNDYiLCI2MzY5MWZiOWVkOTQ5MzQ5MWNjYWEzMGQiLCI2MzY5YjY0MGRiNWM2OTE1ZmU4N2ViZGEiLCI2MzY5YjZlOWRiNWM2OTE1ZmU4N2ViZmYiLCI2MzY5YjkyMmM3ZGZkZGM0MmVhZGJjZTAiLCI2MzY5YmM0YzYyZWE5MmQ2ZDlhYmIyZGQiLCI2MzZhN2JmYzAyMWMyZDkyMGUzYjY5ZDAiLCI2MzgxZDJmZjk3MmUxZGMwNjFiZmE5OTUiLCI2MzhhZjdjNGFkOGQzOGJhOTJhNTQ4Y2MiLCI2MzhhZmU3N2M2ZWU1MWZjMzE2MmE3M2UiLCI2MzhiMDUwYmM2ZWU1MWZjMzE2MmE4OGEiLCI2MzhiMDdiYWM2ZWU1MWZjMzE2MmE5MDQiXSwiaWF0IjoxNjcwMjU0ODkzLCJleHAiOjE2NzAyNTY2OTN9.l9vxNhn-4TswYG4QEtwf_0FD7jzJp1O5j2L2Rbn0gyQ

###get participant by room
#GET http://localhost:8080/api/participant/room/{{rid}}
GET http://localhost:8080/api/participant/room/638b07bac6ee51fc3162a903
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiU0ltNVY3cGVrUFR3aFRaNFRHdzIzRDRGcFRzMSIsInBhcnRpY2lwYW50cyI6WyI2MzY0ZTAxZmE3ZWMwODQ5OGRkOWJhYTciLCI2MzY0ZTA3ZmE3ZWMwODQ5OGRkOWJhYzMiLCI2MzY1MzY1NTQwMDVmZDMwOWEwYTdkMzAiLCI2MzY1MzhkYTQwMDVmZDMwOWEwYTdkODAiLCI2MzY4OTBlNWFmNDZhZjMzNjAzZjU1MGMiLCI2MzZhN2JmYzAyMWMyZDkyMGUzYjY5ZDciLCI2MzZiNDRjY2JjNzVmODc5Zjg2NGU0MmMiLCI2MzgxZDMwMDk3MmUxZGMwNjFiZmE5OWMiLCI2MzhhZjdjNGFkOGQzOGJhOTJhNTQ4ZDMiLCI2MzhhZmU3OGM2ZWU1MWZjMzE2MmE3NDUiLCI2MzhiMDUyY2M2ZWU1MWZjMzE2MmE4OTEiLCI2MzhiMDdiYmM2ZWU1MWZjMzE2MmE5MGYiXSwiaWF0IjoxNjcwMjUwNTIxLCJleHAiOjE2NzAyNTIzMjF9.YiADvHENAp1-IlkAjk6tXFY9ovmYcV8dP8HF-fQAeUg
###update Participant
#PUT http://localhost:8080/api/participant/{{participantId}}
PUT http://localhost:8080/api/participant/6364e01fa7ec08498dd9ba9f
content-type: Application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNlVqNjMweWppalNZTEFFdlExV0w5MFRmZHJhMiIsInBhcnRpY2lwYW50cyI6WyI2MzY0ZTAxZmE3ZWMwODQ5OGRkOWJhOWYiLCI2MzY0ZTA3ZmE3ZWMwODQ5OGRkOWJhYmMiLCI2MzY1MzY1NDQwMDVmZDMwOWEwYTdkMjkiLCI2MzY1MzhkYTQwMDVmZDMwOWEwYTdkNzkiLCI2MzY4OTBlNWFmNDZhZjMzNjAzZjU1MGIiLCI2MzY4YmQyZTZlMzBjMjQ3YzQxMThkNDYiLCI2MzY5MWZiOWVkOTQ5MzQ5MWNjYWEzMGQiLCI2MzY5YjY0MGRiNWM2OTE1ZmU4N2ViZGEiLCI2MzY5YjZlOWRiNWM2OTE1ZmU4N2ViZmYiLCI2MzY5YjkyMmM3ZGZkZGM0MmVhZGJjZTAiLCI2MzY5YmM0YzYyZWE5MmQ2ZDlhYmIyZGQiLCI2MzZhN2JmYzAyMWMyZDkyMGUzYjY5ZDAiLCI2MzgxZDJmZjk3MmUxZGMwNjFiZmE5OTUiLCI2MzhhZjdjNGFkOGQzOGJhOTJhNTQ4Y2MiLCI2MzhhZmU3N2M2ZWU1MWZjMzE2MmE3M2UiLCI2MzhiMDUwYmM2ZWU1MWZjMzE2MmE4OGEiLCI2MzhiMDdiYWM2ZWU1MWZjMzE2MmE5MDQiXSwiaWF0IjoxNjcwMjU0ODkzLCJleHAiOjE2NzAyNTY2OTN9.l9vxNhn-4TswYG4QEtwf_0FD7jzJp1O5j2L2Rbn0gyQ

{
  "nickname": "dHVhbg==",
  "isAdmin": true,
  "allowSendMSG": true,
  "allowSendFile": true,
  "allowViewFile": true
}

###delete Participant
#DELETE http://localhost:8080/api/participant/{{participantId}}
DELETE http://localhost:8080/api/participant/634ab817319f231d0db6e75f

###delete all Participant
#DELETE http://localhost:8080/api/participant/
DELETE http://localhost:8080/api/participant/

###login
#POST http://localhost:8080/auth/login/{{user_id}}
POST http://localhost:8080/api/auth/login/6Uj630yjijSYLAEvQ1WL90Tfdra2
Content-Type: application/json