#1
//create participant
#POST http://localhost:8080/api/participant/:userId&:roomId
POST http://localhost:8080/api/participant/102190032&634ab817319f231d0db6e75e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjJkN2I4YWYyNmE1NTliZDhmOTRkNDA3IiwiaWF0IjoxNjU4Nzk5MDIyfQ.Xi-0E_F_5aqI_zICxPre-4XgRUIazLVIk3iJUviN1gk

###2
//get All Participant
#GET http://localhost:8080/api/participant/
GET http://localhost:8080/api/participant/

###3
//update Participant
#PUT http://localhost:8080/api/participant/{{participantId}}
PUT http://localhost:8080/api/participant/634ab817319f231d0db6e75f
content-type: Application/json

{
  "nickname": "wibu",
  "isAdmin": false,
  "allowSendMSG": true,
  "allowSendFile": true,
  "allowViewFile": true
}

###4
//delete Participant
#DELETE http://localhost:8080/api/participant/{{participantId}}
DELETE http://localhost:8080/api/participant/634ab817319f231d0db6e75f

###5
//delete all Participant
#DELETE http://localhost:8080/api/participant/
DELETE http://localhost:8080/api/participant/