###create room group
#POST http://localhost:8080/api/room/userId
POST http://localhost:8080/api/room/102190031
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjJkN2I4YWYyNmE1NTliZDhmOTRkNDA3IiwiaWF0IjoxNjU4Nzk5MDIyfQ.Xi-0E_F_5aqI_zICxPre-4XgRUIazLVIk3iJUviN1gk

{
  "name": "GROUPOF31",
  "image_ic": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPBQsJdUtRvv2fgMH4600MAsOLZIUZsFsXU4WqAc6NdQ&s"
}

###create room private
#POST http://localhost:8080/api/room/private/userId&receiveId
POST http://localhost:8080/api/room/private/102190030&102190031


###get all room
GET http://localhost:8080/api/room/


###get room by ID user and room
#GET http://localhost:8080/api/room/{{userId}}&{{roomId}}
GET http://localhost:8080/api/room/A931rAdlZATBBnWaySfO2UuQO8v2&6364e01fa7ec08498dd9ba9e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiQTkzMXJBZGxaQVRCQm5XYXlTZk8yVXVRTzh2MiIsInBhcnRpY2lwYW50cyI6WyI2MzY0ZTAxZmE3ZWMwODQ5OGRkOWJhYWUiLCI2MzY0ZTA4MGE3ZWMwODQ5OGRkOWJhYzkiLCI2MzY1MzY1NTQwMDVmZDMwOWEwYTdkMzYiLCI2MzY1MzhkYTQwMDVmZDMwOWEwYTdkODYiLCI2MzY4YmQyZTZlMzBjMjQ3YzQxMThkNDciLCI2MzY5MjU1ZmVkOTQ5MzQ5MWNjYWE1OGYiLCI2MzZhN2JmZDAyMWMyZDkyMGUzYjY5ZGQiLCI2MzZiNDRjY2JjNzVmODc5Zjg2NGU0MmIiLCI2MzgxZDMwMDk3MmUxZGMwNjFiZmE5YTIiXSwiaWF0IjoxNjY5ODg5ODg5LCJleHAiOjE2Njk4ODk5MTl9.OEcQuzLu_SekB_4R5sNIKnCOk884oxnylIDQ-ax15vQ

###get private room by userId
#GET http://localhost:8080/api/room//private/{{userId}}
GET http://localhost:8080/api/room/private/SIm5V7pekPTwhTZ4TGw23D4FpTs1

###get group room by userId
#GET http://localhost:8080/api/room/group/{{userId}}
GET http://localhost:8080/api/room/group/6Uj630yjijSYLAEvQ1WL90Tfdra2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNlVqNjMweWppalNZTEFFdlExV0w5MFRmZHJhMiIsInBhcnRpY2lwYW50cyI6WyI2MzY0ZTAxZmE3ZWMwODQ5OGRkOWJhOWYiLCI2MzY0ZTA3ZmE3ZWMwODQ5OGRkOWJhYmMiLCI2MzY1MzY1NDQwMDVmZDMwOWEwYTdkMjkiLCI2MzY1MzhkYTQwMDVmZDMwOWEwYTdkNzkiLCI2MzY4OTBlNWFmNDZhZjMzNjAzZjU1MGIiLCI2MzY4YmQyZTZlMzBjMjQ3YzQxMThkNDYiLCI2MzY5MWZiOWVkOTQ5MzQ5MWNjYWEzMGQiLCI2MzY5YjY0MGRiNWM2OTE1ZmU4N2ViZGEiLCI2MzY5YjZlOWRiNWM2OTE1ZmU4N2ViZmYiLCI2MzY5YjkyMmM3ZGZkZGM0MmVhZGJjZTAiLCI2MzY5YmM0YzYyZWE5MmQ2ZDlhYmIyZGQiLCI2MzZhN2JmYzAyMWMyZDkyMGUzYjY5ZDAiLCI2MzgxZDJmZjk3MmUxZGMwNjFiZmE5OTUiXSwiaWF0IjoxNjY5OTA3NTYwLCJleHAiOjE2Njk5MTExNjB9.LrfvRxA55MTNPtZPkLi80rBCL85T8IHPyjV-xq_U-Sg


###get private room by userId and partnerId
#GET http://localhost:8080/api/room/check/{{userId}}&{{partnerId}}
GET http://localhost:8080/api/room/check/6Uj630yjijSYLAEvQ1WL90Tfdra2&A931rAdlZATBBnWaySfO2UuQO8v2

###get room by userId
#GET http://localhost:8080/api/room/{{userId}}
GET http://localhost:8080/api/room/SIm5V7pekPTwhTZ4TGw23D4FpTs1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiU0ltNVY3cGVrUFR3aFRaNFRHdzIzRDRGcFRzMSIsInBhcnRpY2lwYW50cyI6WyI2MzY0ZTAxZmE3ZWMwODQ5OGRkOWJhYTciLCI2MzY0ZTA3ZmE3ZWMwODQ5OGRkOWJhYzMiLCI2MzY1MzY1NTQwMDVmZDMwOWEwYTdkMzAiLCI2MzY1MzhkYTQwMDVmZDMwOWEwYTdkODAiLCI2MzY4OTBlNWFmNDZhZjMzNjAzZjU1MGMiLCI2MzZhN2JmYzAyMWMyZDkyMGUzYjY5ZDciLCI2MzZiNDRjY2JjNzVmODc5Zjg2NGU0MmMiLCI2MzgxZDMwMDk3MmUxZGMwNjFiZmE5OWMiXSwiaWF0IjoxNjY5OTA5MTY0LCJleHAiOjE2Njk5MTI3NjR9.k8UtNL_dyzhhWtercyk93pk9u-kw9QrS2fvNklUWvq0

###delete room
#DELETE http://localhost:8080/api/room/{{rId}}
DELETE http://localhost:8080/api/room/6364e01fa7ec08498dd9ba9e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiU0ltNVY3cGVrUFR3aFRaNFRHdzIzRDRGcFRzMSIsInBhcnRpY2lwYW50cyI6WyI2MzY0ZTAxZmE3ZWMwODQ5OGRkOWJhYTciLCI2MzY0ZTA3ZmE3ZWMwODQ5OGRkOWJhYzMiLCI2MzY1MzY1NTQwMDVmZDMwOWEwYTdkMzAiLCI2MzY1MzhkYTQwMDVmZDMwOWEwYTdkODAiLCI2MzY4OTBlNWFmNDZhZjMzNjAzZjU1MGMiLCI2MzZhN2JmYzAyMWMyZDkyMGUzYjY5ZDciLCI2MzZiNDRjY2JjNzVmODc5Zjg2NGU0MmMiLCI2MzgxZDMwMDk3MmUxZGMwNjFiZmE5OWMiXSwiaWF0IjoxNjY5OTA5MTY0LCJleHAiOjE2Njk5MTI3NjR9.k8UtNL_dyzhhWtercyk93pk9u-kw9QrS2fvNklUWvq0

###delete all room
#DELETE http://localhost:8080/api/room/all/
DELETE http://localhost:8080/api/room/

###login
#POST http://localhost:8080/auth/login/{{user_id}}
POST http://localhost:8080/auth/login/SIm5V7pekPTwhTZ4TGw23D4FpTs1
Content-Type: application/json

###
//Lấy tất cả các room mà user tham gia (private và group)
//Trả về list có đối tượng như sau
#{
#  "success": true
#  "data": {
#    ... các thuộc tính của room
#    "message": [  // 10 tin nhắn gần nhất của room (pagination with page = 0 and step = 10)
#      {
#        ... các thuộc tính của message,
#        "user": {} // user gửi tin nhắn này
#      },
#      {},
#      {},
#      ...
#    ],
#    "user": {} // nếu room.type == private thì user này đối phương, nếu room.type == group thì user = null
#    "particpant: {} //particpant.user_id = uid
#  }
#}

#{
#  data: {
#    ... các thuộc tính của room,
#    "message": [],
#    "user": {},
#    "participant": {}
#  }
#}
#
#"success": true,
#  "data": [
#    {
#      "room_id": "635e3553b6faacb06ced6782",
#      "name": "R1JPVVBPRjMx",
#      "image_ic": "aHR0cHM6Ly9lbmNyeXB0ZWQtdGJuMC5nc3RhdGljLmNvbS9pbWFnZXM/cT10Ym46QU5kOUdjUlBCUXNKZFV0UnZ2MmZnTUg0NjAwTUFzT0xaSVVac0ZzWFU0V3FBYzZOZFEmcw==",
#      "type": "group",
#      "messages": [
#        {
#          "_id": "6361e585d609d4c758cde92f",
#          "message": "dGV4dDE=",
#          "time": "2022-11-02T03:35:33.607Z",
#          "type": "dGV4dA==",
#          "user_id": "6361dfbad609d4c758cde8e1",
#          "room_id": "635e3553b6faacb06ced6782",
#          "__v": 0
#        },
#        {
#          "_id": "6361e58ad609d4c758cde936",
#          "message": "dGV4dDI=",
#          "time": "2022-11-02T03:35:38.842Z",
#          "type": "dGV4dA==",
#          "user_id": "6361dfbad609d4c758cde8e1",
#          "room_id": "635e3553b6faacb06ced6782",
#          "__v": 0
#        },
#        {
#          "_id": "6361e58ed609d4c758cde93d",
#          "message": "dGV4dDM=",
#          "time": "2022-11-02T03:35:42.888Z",
#          "type": "dGV4dA==",
#          "user_id": "6361dfbad609d4c758cde8e1",
#          "room_id": "635e3553b6faacb06ced6782",
#          "__v": 0
#        }
#      ],
#      "user": null,
#      "participant": {
#        "_id": "6361e21bd609d4c758cde908",
#        "nickname": "ZEhWaGJnPT0=",
#        "isAdmin": false,
#        "timestamp": "2022-11-02T03:20:59.154Z",
#        "allowSendMSG": true,
#        "allowSendFile": true,
#        "allowViewFile": true,
#        "user_id": "6361dfbad609d4c758cde8e1",
#        "room_id": "635e3553b6faacb06ced6782",
#        "__v": 0
#      }
#    }
#  ]
#}

