#1
//create room group
#POST http://localhost:8080/api/room/userId
POST http://localhost:8080/api/room/102190031
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjJkN2I4YWYyNmE1NTliZDhmOTRkNDA3IiwiaWF0IjoxNjU4Nzk5MDIyfQ.Xi-0E_F_5aqI_zICxPre-4XgRUIazLVIk3iJUviN1gk

{
  "name": "GROUPOF31",
  "image_ic": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPBQsJdUtRvv2fgMH4600MAsOLZIUZsFsXU4WqAc6NdQ&s"
}

###2
//create room private
#POST http://localhost:8080/api/room/private/userId&receiveId
POST http://localhost:8080/api/room/private/102190030&102190031


###3
//get all room
GET http://localhost:8080/api/room/


###4
//get room by ID user and room+
#GET http://localhost:8080/api/room/{{userId}}&{{roomId}}
GET http://localhost:8080/api/room/A931rAdlZATBBnWaySfO2UuQO8v2&6364e01fa7ec08498dd9ba9e


###5
//get private room by userId
#GET http://localhost:8080/api/room//private/{{userId}}
GET http://localhost:8080/api/room/private/SIm5V7pekPTwhTZ4TGw23D4FpTs1

###6
//get group room by userId
#GET http://localhost:8080/api/room/group/{{userId}}
GET http://localhost:8080/api/room/group/JoXu8k5EKNOaZwUqSHzTQUgXm503


###7
//get private room by userId and partnerId
#GET http://localhost:8080/api/room/check/{{userId}}&{{partnerId}}
GET http://localhost:8080/api/room/check/6Uj630yjijSYLAEvQ1WL90Tfdra2&A931rAdlZATBBnWaySfO2UuQO8v2

###8
//get room by userId
#GET http://localhost:8080/api/room/{{userId}}
GET http://localhost:8080/api/room/6Uj630yjijSYLAEvQ1WL90Tfdra2

###9
//delete room
#DELETE http://localhost:8080/api/room/{{rId}}
DELETE http://localhost:8080/api/room/636538e84005fd309a0a7d97

###10
//delete all room
#DELETE http://localhost:8080/api/room/all/
DELETE http://localhost:8080/api/room/

###
//Lấy tất cả các room mà user tham gia (private và group)
//Trả về list có đối tượng như sau
#{
#  "success": true
#  "data": {
#    ... các thuộc tính của room
#    "message": [  // 10 tin nhắn gần nhất của room (pagination with page = 0 and step = 10)
#      {
#        ... các thuộc tính của message,
#        "user": {} // user gửi tin nhắn này
#      },
#      {},
#      {},
#      ...
#    ],
#    "user": {} // nếu room.type == private thì user này đối phương, nếu room.type == group thì user = null
#    "particpant: {} //particpant.user_id = uid
#  }
#}

#{
#  data: {
#    ... các thuộc tính của room,
#    "message": [],
#    "user": {},
#    "participant": {}
#  }
#}
#
#"success": true,
#  "data": [
#    {
#      "room_id": "635e3553b6faacb06ced6782",
#      "name": "R1JPVVBPRjMx",
#      "image_ic": "aHR0cHM6Ly9lbmNyeXB0ZWQtdGJuMC5nc3RhdGljLmNvbS9pbWFnZXM/cT10Ym46QU5kOUdjUlBCUXNKZFV0UnZ2MmZnTUg0NjAwTUFzT0xaSVVac0ZzWFU0V3FBYzZOZFEmcw==",
#      "type": "group",
#      "messages": [
#        {
#          "_id": "6361e585d609d4c758cde92f",
#          "message": "dGV4dDE=",
#          "time": "2022-11-02T03:35:33.607Z",
#          "type": "dGV4dA==",
#          "user_id": "6361dfbad609d4c758cde8e1",
#          "room_id": "635e3553b6faacb06ced6782",
#          "__v": 0
#        },
#        {
#          "_id": "6361e58ad609d4c758cde936",
#          "message": "dGV4dDI=",
#          "time": "2022-11-02T03:35:38.842Z",
#          "type": "dGV4dA==",
#          "user_id": "6361dfbad609d4c758cde8e1",
#          "room_id": "635e3553b6faacb06ced6782",
#          "__v": 0
#        },
#        {
#          "_id": "6361e58ed609d4c758cde93d",
#          "message": "dGV4dDM=",
#          "time": "2022-11-02T03:35:42.888Z",
#          "type": "dGV4dA==",
#          "user_id": "6361dfbad609d4c758cde8e1",
#          "room_id": "635e3553b6faacb06ced6782",
#          "__v": 0
#        }
#      ],
#      "user": null,
#      "participant": {
#        "_id": "6361e21bd609d4c758cde908",
#        "nickname": "ZEhWaGJnPT0=",
#        "isAdmin": false,
#        "timestamp": "2022-11-02T03:20:59.154Z",
#        "allowSendMSG": true,
#        "allowSendFile": true,
#        "allowViewFile": true,
#        "user_id": "6361dfbad609d4c758cde8e1",
#        "room_id": "635e3553b6faacb06ced6782",
#        "__v": 0
#      }
#    }
#  ]
#}

