//create user
#POST http://localhost:8080/api/user/
POST http://localhost:8080/api/user/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjJkN2I4YWYyNmE1NTliZDhmOTRkNDA3IiwiaWF0IjoxNjU4Nzk5MDIyfQ.Xi-0E_F_5aqI_zICxPre-4XgRUIazLVIk3iJUviN1gk

{
  "user_id": "102190030",
  "name": "wibu",
  "age": 21,
  "phone": "0123456739",
  "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPBQsJdUtRvv2fgMH4600MAsOLZIUZsFsXU4WqAc6NdQ&s"
}

###2
//get all user
GET http://localhost:8080/api/user/

###3
//delete room
#DELETE http://localhost:8080/api/user/{{uid}}
DELETE http://localhost:8080/api/user/{{uid}}